<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PortfolioContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Services Data
        $services = [
            [
                'slug' => 'web-development',
                'icon' => 'code',
                'sort_order' => 1,
                'title_en' => 'Web Development',
                'description_en' => 'Full-stack web applications using modern frameworks like Laravel, Vue.js, and React.',
                'title_ar' => 'تطوير الويب',
                'description_ar' => 'تطبيقات ويب شاملة باستخدام أطر عمل حديثة مثل Laravel و Vue.js و React.',
                'technologies_en' => json_encode(['Laravel', 'Vue.js', 'React', 'Tailwind CSS', 'MySQL']),
                'technologies_ar' => json_encode(['Laravel', 'Vue.js', 'React', 'Tailwind CSS', 'MySQL']),
                'features_en' => json_encode(['Responsive Design', 'RESTful APIs', 'Database Architecture', 'Performance Optimization']),
                'features_ar' => json_encode(['تصميم متجاوب', 'واجهات برمجة التطبيقات RESTful', 'هندسة قواعد البيانات', 'تحسين الأداء']),
            ],
            [
                'slug' => 'ai-machine-learning',
                'icon' => 'brain',
                'sort_order' => 2,
                'title_en' => 'AI & Machine Learning',
                'description_en' => 'Custom AI solutions including computer vision, NLP, and predictive analytics.',
                'title_ar' => 'الذكاء الاصطناعي وتعلم الآلة',
                'description_ar' => 'حلول ذكاء اصطناعي مخصصة بما في ذلك رؤية الكمبيوتر، معالجة اللغات الطبيعية، والتحليل التنبؤي.',
                'technologies_en' => json_encode(['Python', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'OpenCV']),
                'technologies_ar' => json_encode(['Python', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'OpenCV']),
                'features_en' => json_encode(['Computer Vision', 'Natural Language Processing', 'Predictive Analytics', 'Deep Learning']),
                'features_ar' => json_encode(['رؤية الكمبيوتر', 'معالجة اللغات الطبيعية', 'التحليل التنبؤي', 'التعلم العميق']),
            ],
            [
                'slug' => 'iot-solutions',
                'icon' => 'microchip',
                'sort_order' => 3,
                'title_en' => 'IoT Solutions',
                'description_en' => 'Smart home systems, sensor networks, and embedded systems development.',
                'title_ar' => 'حلول إنترنت الأشياء',
                'description_ar' => 'أنظمة المنازل الذكية، شبكات المستشعرات، وتطوير الأنظمة المدمجة.',
                'technologies_en' => json_encode(['Arduino', 'Raspberry Pi', 'ESP32', 'MQTT', 'Node-RED']),
                'technologies_ar' => json_encode(['Arduino', 'Raspberry Pi', 'ESP32', 'MQTT', 'Node-RED']),
                'features_en' => json_encode(['Smart Home Automation', 'Sensor Networks', 'Embedded Systems', 'Real-time Monitoring']),
                'features_ar' => json_encode(['أتمتة المنازل الذكية', 'شبكات المستشعرات', 'الأنظمة المدمجة', 'المراقبة في الوقت الفعلي']),
            ],
            [
                'slug' => 'database-design',
                'icon' => 'database',
                'sort_order' => 4,
                'title_en' => 'Database Design',
                'description_en' => 'Efficient database architecture and optimization for scalable applications.',
                'title_ar' => 'تصميم قواعد البيانات',
                'description_ar' => 'هندسة قواعد بيانات فعالة وتحسين للتطبيقات القابلة للتوسع.',
                'technologies_en' => json_encode(['MySQL', 'PostgreSQL', 'MongoDB', 'Redis', 'Elasticsearch']),
                'technologies_ar' => json_encode(['MySQL', 'PostgreSQL', 'MongoDB', 'Redis', 'Elasticsearch']),
                'features_en' => json_encode(['Database Architecture', 'Query Optimization', 'Data Modeling', 'Performance Tuning']),
                'features_ar' => json_encode(['هندسة قواعد البيانات', 'تحسين الاستعلامات', 'نمذجة البيانات', 'ضبط الأداء']),
            ],
            [
                'slug' => 'technical-consulting',
                'icon' => 'lightbulb',
                'sort_order' => 5,
                'title_en' => 'Technical Consulting',
                'description_en' => 'Expert advice on technology stack selection and system architecture.',
                'title_ar' => 'الاستشارات التقنية',
                'description_ar' => 'نصائح خبراء في اختيار مكدس التقنية وهندسة الأنظمة.',
                'technologies_en' => json_encode(['System Design', 'Architecture Review', 'Technology Assessment', 'Performance Analysis']),
                'technologies_ar' => json_encode(['تصميم الأنظمة', 'مراجعة الهندسة', 'تقييم التقنية', 'تحليل الأداء']),
                'features_en' => json_encode(['System Architecture', 'Technology Stack Selection', 'Performance Analysis', 'Best Practices']),
                'features_ar' => json_encode(['هندسة الأنظمة', 'اختيار مكدس التقنية', 'تحليل الأداء', 'أفضل الممارسات']),
            ],
        ];

        DB::table('services')->insert($services);

        // Statistics Data
        $statistics = [
            [
                'key' => 'projects_completed',
                'type' => 'number',
                'value' => 25,
                'sort_order' => 1,
                'label_en' => 'Projects Completed',
                'label_ar' => 'المشاريع المكتملة',
                'suffix' => '+',
                'icon' => 'briefcase',
                'color' => '#06b6d4',
            ],
            [
                'key' => 'years_experience',
                'type' => 'number',
                'value' => 3,
                'sort_order' => 2,
                'label_en' => 'Years Experience',
                'label_ar' => 'سنوات الخبرة',
                'suffix' => '+',
                'icon' => 'calendar',
                'color' => '#10b981',
            ],
            [
                'key' => 'happy_clients',
                'type' => 'number',
                'value' => 15,
                'sort_order' => 3,
                'label_en' => 'Happy Clients',
                'label_ar' => 'العملاء السعداء',
                'suffix' => '+',
                'icon' => 'users',
                'color' => '#f59e0b',
            ],
            [
                'key' => 'technologies_mastered',
                'type' => 'number',
                'value' => 20,
                'sort_order' => 4,
                'label_en' => 'Technologies',
                'label_ar' => 'التقنيات',
                'suffix' => '+',
                'icon' => 'code',
                'color' => '#8b5cf6',
            ],
        ];

        DB::table('statistics')->insert($statistics);

        // Skills Data
        $skills = [
            // Web Development Skills
            [
                'slug' => 'laravel',
                'category' => 'web_development',
                'proficiency_level' => 90,
                'years_experience' => 3,
                'sort_order' => 1,
                'name_en' => 'Laravel',
                'name_ar' => 'Laravel',
                'description_en' => 'PHP framework for web application development',
                'description_ar' => 'إطار عمل PHP لتطوير تطبيقات الويب',
                'color' => '#ff2d20',
            ],
            [
                'slug' => 'vue-js',
                'category' => 'web_development',
                'proficiency_level' => 85,
                'years_experience' => 2,
                'sort_order' => 2,
                'name_en' => 'Vue.js',
                'name_ar' => 'Vue.js',
                'description_en' => 'Progressive JavaScript framework for building UIs',
                'description_ar' => 'إطار عمل JavaScript تقدمي لبناء واجهات المستخدم',
                'color' => '#4fc08d',
            ],
            [
                'slug' => 'react',
                'category' => 'web_development',
                'proficiency_level' => 80,
                'years_experience' => 2,
                'sort_order' => 3,
                'name_en' => 'React',
                'name_ar' => 'React',
                'description_en' => 'JavaScript library for building user interfaces',
                'description_ar' => 'مكتبة JavaScript لبناء واجهات المستخدم',
                'color' => '#61dafb',
            ],
            [
                'slug' => 'javascript',
                'category' => 'web_development',
                'proficiency_level' => 92,
                'years_experience' => 3,
                'sort_order' => 4,
                'name_en' => 'JavaScript',
                'name_ar' => 'JavaScript',
                'description_en' => 'Programming language for web development',
                'description_ar' => 'لغة برمجة لتطوير الويب',
                'color' => '#f7df1e',
            ],
            [
                'slug' => 'php',
                'category' => 'web_development',
                'proficiency_level' => 88,
                'years_experience' => 3,
                'sort_order' => 5,
                'name_en' => 'PHP',
                'name_ar' => 'PHP',
                'description_en' => 'Server-side scripting language',
                'description_ar' => 'لغة برمجة من جانب الخادم',
                'color' => '#777bb4',
            ],
            [
                'slug' => 'tailwind-css',
                'category' => 'web_development',
                'proficiency_level' => 85,
                'years_experience' => 2,
                'sort_order' => 6,
                'name_en' => 'Tailwind CSS',
                'name_ar' => 'Tailwind CSS',
                'description_en' => 'Utility-first CSS framework',
                'description_ar' => 'إطار عمل CSS قائم على الأدوات المساعدة',
                'color' => '#06b6d4',
            ],
            [
                'slug' => 'mysql',
                'category' => 'web_development',
                'proficiency_level' => 82,
                'years_experience' => 3,
                'sort_order' => 7,
                'name_en' => 'MySQL',
                'name_ar' => 'MySQL',
                'description_en' => 'Relational database management system',
                'description_ar' => 'نظام إدارة قواعد البيانات العلائقية',
                'color' => '#4479a1',
            ],
            // AI/ML Skills
            [
                'slug' => 'python',
                'category' => 'ai_ml',
                'proficiency_level' => 88,
                'years_experience' => 3,
                'sort_order' => 1,
                'name_en' => 'Python',
                'name_ar' => 'Python',
                'description_en' => 'Programming language for AI and data science',
                'description_ar' => 'لغة برمجة للذكاء الاصطناعي وعلم البيانات',
                'color' => '#3776ab',
            ],
            [
                'slug' => 'tensorflow',
                'category' => 'ai_ml',
                'proficiency_level' => 75,
                'years_experience' => 2,
                'sort_order' => 2,
                'name_en' => 'TensorFlow',
                'name_ar' => 'TensorFlow',
                'description_en' => 'Open-source machine learning framework',
                'description_ar' => 'إطار عمل تعلم الآلة مفتوح المصدر',
                'color' => '#ff6f00',
            ],
            [
                'slug' => 'pytorch',
                'category' => 'ai_ml',
                'proficiency_level' => 70,
                'years_experience' => 2,
                'sort_order' => 3,
                'name_en' => 'PyTorch',
                'name_ar' => 'PyTorch',
                'description_en' => 'Deep learning framework',
                'description_ar' => 'إطار عمل للتعلم العميق',
                'color' => '#ee4c2c',
            ],
            [
                'slug' => 'scikit-learn',
                'category' => 'ai_ml',
                'proficiency_level' => 80,
                'years_experience' => 2,
                'sort_order' => 4,
                'name_en' => 'Scikit-learn',
                'name_ar' => 'Scikit-learn',
                'description_en' => 'Machine learning library for Python',
                'description_ar' => 'مكتبة تعلم الآلة لـ Python',
                'color' => '#f7931e',
            ],
            [
                'slug' => 'opencv',
                'category' => 'ai_ml',
                'proficiency_level' => 78,
                'years_experience' => 2,
                'sort_order' => 5,
                'name_en' => 'OpenCV',
                'name_ar' => 'OpenCV',
                'description_en' => 'Computer vision library',
                'description_ar' => 'مكتبة رؤية الكمبيوتر',
                'color' => '#5cc8ee',
            ],
            [
                'slug' => 'pandas',
                'category' => 'ai_ml',
                'proficiency_level' => 85,
                'years_experience' => 2,
                'sort_order' => 6,
                'name_en' => 'Pandas',
                'name_ar' => 'Pandas',
                'description_en' => 'Data manipulation and analysis library',
                'description_ar' => 'مكتبة معالجة وتحليل البيانات',
                'color' => '#150458',
            ],
            // IoT Skills
            [
                'slug' => 'arduino',
                'category' => 'embedded_iot',
                'proficiency_level' => 85,
                'years_experience' => 2,
                'sort_order' => 1,
                'name_en' => 'Arduino',
                'name_ar' => 'Arduino',
                'description_en' => 'Open-source electronics platform',
                'description_ar' => 'منصة إلكترونيات مفتوحة المصدر',
                'color' => '#00979d',
            ],
            [
                'slug' => 'raspberry-pi',
                'category' => 'embedded_iot',
                'proficiency_level' => 80,
                'years_experience' => 2,
                'sort_order' => 2,
                'name_en' => 'Raspberry Pi',
                'name_ar' => 'Raspberry Pi',
                'description_en' => 'Single-board computer for IoT projects',
                'description_ar' => 'كمبيوتر بلوحة واحدة لمشاريع إنترنت الأشياء',
                'color' => '#c51a4a',
            ],
            [
                'slug' => 'esp32',
                'category' => 'embedded_iot',
                'proficiency_level' => 75,
                'years_experience' => 2,
                'sort_order' => 3,
                'name_en' => 'ESP32',
                'name_ar' => 'ESP32',
                'description_en' => 'Wi-Fi and Bluetooth microcontroller',
                'description_ar' => 'متحكم دقيق مع Wi-Fi و Bluetooth',
                'color' => '#000000',
            ],
            [
                'slug' => 'mqtt',
                'category' => 'embedded_iot',
                'proficiency_level' => 82,
                'years_experience' => 2,
                'sort_order' => 4,
                'name_en' => 'MQTT',
                'name_ar' => 'MQTT',
                'description_en' => 'Lightweight messaging protocol for IoT',
                'description_ar' => 'بروتوكول مراسلة خفيف لإنترنت الأشياء',
                'color' => '#ff6600',
            ],
            [
                'slug' => 'node-red',
                'category' => 'embedded_iot',
                'proficiency_level' => 70,
                'years_experience' => 1,
                'sort_order' => 5,
                'name_en' => 'Node-RED',
                'name_ar' => 'Node-RED',
                'description_en' => 'Flow-based programming for IoT',
                'description_ar' => 'برمجة قائمة على التدفق لإنترنت الأشياء',
                'color' => '#8f0000',
            ],
            [
                'slug' => 'embedded-c',
                'category' => 'embedded_iot',
                'proficiency_level' => 72,
                'years_experience' => 2,
                'sort_order' => 6,
                'name_en' => 'Embedded C',
                'name_ar' => 'Embedded C',
                'description_en' => 'Programming language for embedded systems',
                'description_ar' => 'لغة برمجة للأنظمة المدمجة',
                'color' => '#00599c',
            ],
            [
                'slug' => 'nodemcu',
                'category' => 'embedded_iot',
                'proficiency_level' => 78,
                'years_experience' => 2,
                'sort_order' => 7,
                'name_en' => 'NodeMCU',
                'name_ar' => 'NodeMCU',
                'description_en' => 'WiFi-based microcontroller board',
                'description_ar' => 'لوحة متحكم دقيقة قائمة على WiFi',
                'color' => '#000000',
            ],
            [
                'slug' => 'coap',
                'category' => 'embedded_iot',
                'proficiency_level' => 65,
                'years_experience' => 1,
                'sort_order' => 8,
                'name_en' => 'CoAP',
                'name_ar' => 'CoAP',
                'description_en' => 'Constrained Application Protocol for IoT',
                'description_ar' => 'بروتوكول التطبيق المقيد لإنترنت الأشياء',
                'color' => '#00a652',
            ],
            [
                'slug' => 'zigbee',
                'category' => 'embedded_iot',
                'proficiency_level' => 60,
                'years_experience' => 1,
                'sort_order' => 9,
                'name_en' => 'Zigbee',
                'name_ar' => 'Zigbee',
                'description_en' => 'Wireless communication protocol for IoT',
                'description_ar' => 'بروتوكول الاتصال اللاسلكي لإنترنت الأشياء',
                'color' => '#ff6600',
            ],
            [
                'slug' => 'lopy',
                'category' => 'embedded_iot',
                'proficiency_level' => 68,
                'years_experience' => 1,
                'sort_order' => 10,
                'name_en' => 'LoPy',
                'name_ar' => 'LoPy',
                'description_en' => 'LoRa and WiFi microcontroller',
                'description_ar' => 'متحكم دقيق LoRa و WiFi',
                'color' => '#00599c',
            ],
            [
                'slug' => 'micropython',
                'category' => 'embedded_iot',
                'proficiency_level' => 80,
                'years_experience' => 2,
                'sort_order' => 11,
                'name_en' => 'MicroPython',
                'name_ar' => 'MicroPython',
                'description_en' => 'Python implementation for microcontrollers',
                'description_ar' => 'تطبيق Python للمتحكمات الدقيقة',
                'color' => '#3776ab',
            ],
            [
                'slug' => 'circuitpython',
                'category' => 'embedded_iot',
                'proficiency_level' => 75,
                'years_experience' => 2,
                'sort_order' => 12,
                'name_en' => 'CircuitPython',
                'name_ar' => 'CircuitPython',
                'description_en' => 'Python for hardware programming',
                'description_ar' => 'Python لبرمجة الأجهزة',
                'color' => '#000000',
            ],
            [
                'slug' => 'freertos',
                'category' => 'embedded_iot',
                'proficiency_level' => 70,
                'years_experience' => 1,
                'sort_order' => 13,
                'name_en' => 'FreeRTOS',
                'name_ar' => 'FreeRTOS',
                'description_en' => 'Real-time operating system for embedded systems',
                'description_ar' => 'نظام تشغيل في الوقت الفعلي للأنظمة المدمجة',
                'color' => '#ff6600',
            ],
            // Programming Languages Skills
            [
                'slug' => 'cpp',
                'category' => 'programming_languages',
                'proficiency_level' => 75,
                'years_experience' => 2,
                'sort_order' => 1,
                'name_en' => 'C++',
                'name_ar' => 'C++',
                'description_en' => 'High-performance programming language',
                'description_ar' => 'لغة برمجة عالية الأداء',
                'color' => '#00599c',
            ],
            [
                'slug' => 'java',
                'category' => 'programming_languages',
                'proficiency_level' => 70,
                'years_experience' => 2,
                'sort_order' => 2,
                'name_en' => 'Java',
                'name_ar' => 'Java',
                'description_en' => 'Object-oriented programming language',
                'description_ar' => 'لغة برمجة كائنية التوجه',
                'color' => '#007396',
            ],
            [
                'slug' => 'sql',
                'category' => 'programming_languages',
                'proficiency_level' => 85,
                'years_experience' => 3,
                'sort_order' => 3,
                'name_en' => 'SQL',
                'name_ar' => 'SQL',
                'description_en' => 'Database query language',
                'description_ar' => 'لغة استعلام قواعد البيانات',
                'color' => '#336791',
            ],
            [
                'slug' => 'html-css',
                'category' => 'programming_languages',
                'proficiency_level' => 90,
                'years_experience' => 3,
                'sort_order' => 4,
                'name_en' => 'HTML/CSS',
                'name_ar' => 'HTML/CSS',
                'description_en' => 'Web markup and styling languages',
                'description_ar' => 'لغات ترميز وتنسيق الويب',
                'color' => '#e34c26',
            ],
            // Tools & Platforms Skills
            [
                'slug' => 'git',
                'category' => 'tools_platforms',
                'proficiency_level' => 88,
                'years_experience' => 3,
                'sort_order' => 1,
                'name_en' => 'Git',
                'name_ar' => 'Git',
                'description_en' => 'Version control system',
                'description_ar' => 'نظام التحكم في الإصدارات',
                'color' => '#f05032',
            ],
            [
                'slug' => 'docker',
                'category' => 'tools_platforms',
                'proficiency_level' => 72,
                'years_experience' => 1,
                'sort_order' => 2,
                'name_en' => 'Docker',
                'name_ar' => 'Docker',
                'description_en' => 'Containerization platform',
                'description_ar' => 'منصة الحاويات',
                'color' => '#2496ed',
            ],
            [
                'slug' => 'vs-code',
                'category' => 'tools_platforms',
                'proficiency_level' => 95,
                'years_experience' => 3,
                'sort_order' => 3,
                'name_en' => 'VS Code',
                'name_ar' => 'VS Code',
                'description_en' => 'Code editor and development environment',
                'description_ar' => 'محرر أكواد وبيئة تطوير',
                'color' => '#007acc',
            ],
            [
                'slug' => 'linux',
                'category' => 'tools_platforms',
                'proficiency_level' => 78,
                'years_experience' => 2,
                'sort_order' => 4,
                'name_en' => 'Linux',
                'name_ar' => 'Linux',
                'description_en' => 'Operating system for development',
                'description_ar' => 'نظام تشغيل للتطوير',
                'color' => '#fcc624',
            ],
            [
                'slug' => 'postman',
                'category' => 'tools_platforms',
                'proficiency_level' => 85,
                'years_experience' => 2,
                'sort_order' => 5,
                'name_en' => 'Postman',
                'name_ar' => 'Postman',
                'description_en' => 'API testing and development tool',
                'description_ar' => 'أداة اختبار وتطوير واجهات برمجة التطبيقات',
                'color' => '#ff6c37',
            ],
        ];

        DB::table('skills')->insert($skills);

        // Projects Data
        $projects = [
            [
                'slug' => 'restful-apis-laravel-sanctum',
                'title_en' => 'RESTful APIs using Laravel and Sanctum',
                'title_ar' => 'واجهات برمجة التطبيقات RESTful باستخدام Laravel و Sanctum',
                'description_en' => 'Built secure RESTful APIs with Laravel framework and Sanctum authentication',
                'description_ar' => 'بناء واجهات برمجة تطبيقات RESTful آمنة باستخدام إطار عمل Laravel ومصادقة Sanctum',
                'content_en' => 'This project demonstrates the creation of a complete RESTful API system using Laravel 10 with Sanctum for authentication. The API includes user management, role-based access control, and comprehensive CRUD operations with proper validation and error handling.',
                'content_ar' => 'يوضح هذا المشروع إنشاء نظام واجهات برمجة تطبيقات RESTful كامل باستخدام Laravel 10 مع Sanctum للمصادقة. تتضمن واجهة برمجة التطبيقات إدارة المستخدمين، والتحكم في الوصول المستند إلى الأدوار، وعمليات CRUD شاملة مع التحقق الصحيح ومعالجة الأخطاء.',
                'category' => 'web',
                'technologies_en' => json_encode(['Laravel', 'PHP', 'MySQL', 'Sanctum', 'REST API', 'JWT']),
                'technologies_ar' => json_encode(['Laravel', 'PHP', 'MySQL', 'Sanctum', 'REST API', 'JWT']),
                'challenges_en' => json_encode(['Implementing secure authentication', 'Designing scalable API architecture', 'Handling complex data relationships']),
                'challenges_ar' => json_encode(['تنفيذ مصادقة آمنة', 'تصميم بنية واجهة برمجة تطبيقات قابلة للتوسع', 'التعامل مع علاقات البيانات المعقدة']),
                'solutions_en' => json_encode(['Used Laravel Sanctum for token-based authentication', 'Implemented proper API versioning', 'Created comprehensive validation rules']),
                'solutions_ar' => json_encode(['استخدام Laravel Sanctum للمصادقة القائمة على التوكن', 'تنفيذ إصدار واجهة برمجة التطبيقات الصحيح', 'إنشاء قواعد تحقق شاملة']),
                'github_url' => 'https://github.com/Ziad-Abaza/laravel-rest-api',
                'live_url' => 'https://api-demo.ziadportfolio.com',
                'demo_url' => 'https://api-demo.ziadportfolio.com/docs',
                'thumbnail_url' => '/images/projects/restful-api-thumb.jpg',
                'images' => json_encode(['/images/projects/restful-api-1.jpg', '/images/projects/restful-api-2.jpg']),
                'tags' => json_encode(['API', 'Laravel', 'Backend', 'Authentication']),
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
                'completed_at' => '2024-11-15',
                'metadata' => json_encode(['difficulty' => 'intermediate', 'duration' => '3 weeks']),
            ],
            [
                'slug' => 'iot-smart-city-parking',
                'title_en' => 'IoT-based Smart City and Parking Systems',
                'title_ar' => 'أنظمة المدينة الذكية ووقوف السيارات القائمة على إنترنت الأشياء',
                'description_en' => 'Developed IoT solutions for smart city applications including intelligent parking systems',
                'description_ar' => 'تطوير حلول إنترنت الأشياء لتطبيقات المدن الذكية بما في ذلك أنظمة وقوف السيارات الذكية',
                'content_en' => 'A comprehensive IoT solution for smart city parking management. The system uses ultrasonic sensors to detect vehicle presence, MQTT for real-time communication, and a web dashboard for monitoring and control. Features include automatic parking allocation, payment integration, and analytics.',
                'content_ar' => 'حل إنترنت الأشياء شامل لإدارة وقوف السيارات في المدن الذكية. يستخدم النظام مستشعرات فوق صوتية للكشف عن وجود المركبات، و MQTT للتواصل في الوقت الفعلي، ولوحة معلومات ويب للمراقبة والتحكم. تشمل الميزات تخصيص وقوف السيارات تلقائياً، ودمج الدفع، والتحليلات.',
                'category' => 'embedded_iot',
                'technologies_en' => json_encode(['Arduino', 'MQTT', 'Python', 'embedded_iot', 'Smart City', 'NodeMCU']),
                'technologies_ar' => json_encode(['Arduino', 'MQTT', 'Python', 'embedded_iot', 'Smart City', 'NodeMCU']),
                'challenges_en' => json_encode(['Real-time sensor data processing', 'Network reliability issues', 'Power consumption optimization']),
                'challenges_ar' => json_encode(['معالجة بيانات المستشعر في الوقت الفعلي', 'مشاكل موثوقية الشبكة', 'تحسين استهلاك الطاقة']),
                'solutions_en' => json_encode(['Implemented efficient data buffering', 'Used redundant communication protocols', 'Optimized sensor reading intervals']),
                'solutions_ar' => json_encode(['تنفيذ تخزين بيانات فعال', 'استخدام بروتوكولات اتصال زائدة عن الحاجة', 'تحسين فترات قراءة المستشعر']),
                'github_url' => 'https://github.com/Ziad-Abaza/smart-parking-iot',
                'live_url' => null,
                'demo_url' => 'https://youtu.be/demo-iot-parking',
                'thumbnail_url' => '/images/projects/iot-parking-thumb.jpg',
                'images' => json_encode(['/images/projects/iot-parking-1.jpg', '/images/projects/iot-parking-2.jpg']),
                'tags' => json_encode(['embedded_iot', 'Smart City', 'Arduino', 'MQTT']),
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 2,
                'completed_at' => '2024-10-20',
                'metadata' => json_encode(['difficulty' => 'advanced', 'duration' => '6 weeks']),
            ],
            [
                'slug' => 'autonomous-vehicle-lane-detection',
                'title_en' => 'Autonomous Vehicle Lane Detection Systems',
                'title_ar' => 'أنظمة كشف المسارات في المركبات المستقلة',
                'description_en' => 'Implemented computer vision algorithms for lane detection in autonomous vehicles',
                'description_ar' => 'تنفيذ خوارزميات رؤية الكمبيوتر لكشف المسارات في المركبات المستقلة',
                'content_en' => 'Developed a sophisticated lane detection system using computer vision and deep learning. The system processes real-time video streams to detect lane markings, predict vehicle trajectory, and provide steering assistance. Implemented using OpenCV and deep neural networks for high accuracy.',
                'content_ar' => 'تطوير نظام كشف مسارات متطور باستخدام رؤية الكمبيوتر والتعلم العميق. يعالج النظام تدفقات الفيديو في الوقت الفعلي للكشف عن علامات المسارات، والتنبؤ بمسار المركبة، وتوفير مساعدة في التوجيه. تم التنفيذ باستخدام OpenCV والشبكات العصبية العميقة لدقة عالية.',
                'category' => 'ai',
                'technologies_en' => json_encode(['Python', 'OpenCV', 'Computer Vision', 'Deep Learning', 'TensorFlow']),
                'technologies_ar' => json_encode(['Python', 'OpenCV', 'Computer Vision', 'Deep Learning', 'TensorFlow']),
                'challenges_en' => json_encode(['Real-time processing requirements', 'Variable lighting conditions', 'Complex road scenarios']),
                'challenges_ar' => json_encode(['متطلبات المعالجة في الوقت الفعلي', 'ظروف إضاءة متغيرة', 'سيناريوهات طرق معقدة']),
                'solutions_en' => json_encode(['Optimized image processing pipeline', 'Implemented adaptive thresholding', 'Used ensemble of detection algorithms']),
                'solutions_ar' => json_encode(['تحسين خطوة معالجة الصور', 'تنفيذ العتبة التكيفية', 'استخدام مجموعة من خوارزميات الكشف']),
                'github_url' => 'https://github.com/Ziad-Abaza/lane-detection-ai',
                'live_url' => null,
                'demo_url' => 'https://youtu.be/lane-detection-demo',
                'thumbnail_url' => '/images/projects/lane-detection-thumb.jpg',
                'images' => json_encode(['/images/projects/lane-detection-1.jpg', '/images/projects/lane-detection-2.jpg']),
                'tags' => json_encode(['AI', 'Computer Vision', 'Autonomous', 'Deep Learning']),
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 3,
                'completed_at' => '2024-09-10',
                'metadata' => json_encode(['difficulty' => 'advanced', 'duration' => '8 weeks']),
            ],
            [
                'slug' => 'computer-vision-parking-detection',
                'title_en' => 'Computer Vision Parking Detection',
                'title_ar' => 'كشف وقوف السيارات باستخدام رؤية الكمبيوتر',
                'description_en' => 'Created a parking spot detection system using computer vision techniques',
                'description_ar' => 'إنشاء نظام كشف أماكن وقوف السيارات باستخدام تقنيات رؤية الكمبيوتر',
                'content_en' => 'A computer vision system that automatically detects available parking spots in real-time. The system uses CCTV cameras to monitor parking areas, applies image processing algorithms to identify empty spaces, and provides real-time availability updates to drivers through a mobile application.',
                'content_ar' => 'نظام رؤية كمبيوتر يكتشف تلقائياً أماكن وقوف السيارات المتاحة في الوقت الفعلي. يستخدم النظام كاميرات المراقبة لمراقبة مناطق وقوف السيارات، ويطبق خوارزميات معالجة الصور لتحديد المساحات الفارغة، ويوفر تحديثات التوفر في الوقت الفعلي للسائقين من خلال تطبيق الجوال.',
                'category' => 'ai',
                'technologies_en' => json_encode(['Python', 'OpenCV', 'Image Processing', 'Machine Learning']),
                'technologies_ar' => json_encode(['Python', 'OpenCV', 'Image Processing', 'Machine Learning']),
                'challenges_en' => json_encode(['Occlusion handling', 'Weather condition adaptation', 'Real-time performance']),
                'challenges_ar' => json_encode(['التعامل مع الانسداد', 'التكيف مع ظروف الطقس', 'الأداء في الوقت الفعلي']),
                'solutions_en' => json_encode(['Implemented multi-frame analysis', 'Used weather-resistant image enhancement', 'Optimized algorithm for real-time processing']),
                'solutions_ar' => json_encode(['تنفيذ التحليل متعدد الإطارات', 'استخدام تحسين الصور المقاوم للطقس', 'تحسين الخوارزمية للمعالجة في الوقت الفعلي']),
                'github_url' => 'https://github.com/Ziad-Abaza/parking-detection-cv',
                'live_url' => null,
                'demo_url' => 'https://youtu.be/parking-detection-demo',
                'thumbnail_url' => '/images/projects/parking-cv-thumb.jpg',
                'images' => json_encode(['/images/projects/parking-cv-1.jpg', '/images/projects/parking-cv-2.jpg']),
                'tags' => json_encode(['Computer Vision', 'AI', 'Parking', 'Image Processing']),
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 4,
                'completed_at' => '2024-08-15',
                'metadata' => json_encode(['difficulty' => 'intermediate', 'duration' => '4 weeks']),
            ],
            [
                'slug' => 'smart-home-assistant-mqtt',
                'title_en' => 'Smart Home Assistant using MQTT',
                'title_ar' => 'مساعد المنزل الذكي باستخدام MQTT',
                'description_en' => 'Built a smart home automation system with MQTT protocol for device communication',
                'description_ar' => 'بناء نظام أتمتة منزل ذكي باستخدام بروتوكول MQTT للتواصل بين الأجهزة',
                'content_en' => 'A comprehensive smart home automation system that integrates various IoT devices through MQTT protocol. Features include voice control, automated lighting, temperature monitoring, security systems, and energy management. The system includes a web dashboard and mobile app for remote control.',
                'content_ar' => 'نظام أتمتة منزل ذكي شامل يدمج أجهزة إنترنت الأشياء المختلفة من خلال بروتوكول MQTT. تشمل الميزات التحكم الصوتي، والإضاءة الآلية، ومراقبة درجة الحرارة، وأنظمة الأمان، وإدارة الطاقة. يتضمن النظام لوحة معلومات ويب وتطبيق جوال للتحكم عن بعد.',
                'category' => 'embedded_iot',
                'technologies_en' => json_encode(['MQTT', 'embedded_iot', 'Arduino', 'Smart Home', 'Automation']),
                'technologies_ar' => json_encode(['MQTT', 'embedded_iot', 'Arduino', 'Smart Home', 'Automation']),
                'challenges_en' => json_encode(['Device interoperability', 'Network security', 'User interface design']),
                'challenges_ar' => json_encode(['التشغيل البيني للأجهزة', 'أمان الشبكة', 'تصميم واجهة المستخدم']),
                'solutions_en' => json_encode(['Standardized communication protocols', 'Implemented end-to-end encryption', 'Created intuitive dashboard interface']),
                'solutions_ar' => json_encode(['بروتوكولات اتصال موحدة', 'تنفيذ تشفير من طرف إلى طرف', 'إنشاء واجهة لوحة معلومات بديهية']),
                'github_url' => 'https://github.com/Ziad-Abaza/smart-home-mqtt',
                'live_url' => 'https://smarthome.ziadportfolio.com',
                'demo_url' => 'https://youtu.be/smart-home-demo',
                'thumbnail_url' => '/images/projects/smart-home-thumb.jpg',
                'images' => json_encode(['/images/projects/smart-home-1.jpg', '/images/projects/smart-home-2.jpg']),
                'tags' => json_encode(['Smart Home', 'embedded_iot', 'MQTT', 'Automation']),
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 5,
                'completed_at' => '2024-07-20',
                'metadata' => json_encode(['difficulty' => 'intermediate', 'duration' => '5 weeks']),
            ],
            [
                'slug' => 'full-stack-web-applications',
                'title_en' => 'Full-stack Web Applications',
                'title_ar' => 'تطبيقات الويب الشاملة',
                'description_en' => 'Developed multiple full-stack and frontend web applications with modern technologies',
                'description_ar' => 'تطوير تطبيقات ويب شاملة وتطبيقات واجهة أمامية متعددة باستخدام تقنيات حديثة',
                'content_en' => 'A collection of full-stack web applications showcasing various modern web development techniques. Includes e-commerce platforms, social networking applications, content management systems, and real-time collaboration tools. Each project demonstrates different aspects of modern web development.',
                'content_ar' => 'مجموعة من تطبيقات الويب الشاملة التي تعرض تقنيات تطوير الويب الحديثة المختلفة. تشمل منصات التجارة الإلكترونية، وتطبيقات الشبكات الاجتماعية، وأنظمة إدارة المحتوى، وأدوات التعاون في الوقت الفعلي. يوضح كل مشروع جوانب مختلفة من تطوير الويب الحديث.',
                'category' => 'web',
                'technologies_en' => json_encode(['Vue.js', 'Laravel', 'MySQL', 'JavaScript', 'CSS']),
                'technologies_ar' => json_encode(['Vue.js', 'Laravel', 'MySQL', 'JavaScript', 'CSS']),
                'challenges_en' => json_encode(['State management complexity', 'Performance optimization', 'Cross-browser compatibility']),
                'challenges_ar' => json_encode(['تعقيد إدارة الحالة', 'تحسين الأداء', 'التوافق بين المتصفحات']),
                'solutions_en' => json_encode(['Used Vuex for state management', 'Implemented lazy loading and caching', 'Applied progressive enhancement techniques']),
                'solutions_ar' => json_encode(['استخدام Vuex لإدارة الحالة', 'تنفيذ التحميل البطيء والتخزين المؤقت', 'تطبيق تقنيات التحسين التدريجي']),
                'github_url' => 'https://github.com/Ziad-Abaza/fullstack-apps',
                'live_url' => 'https://apps.ziadportfolio.com',
                'demo_url' => null,
                'thumbnail_url' => '/images/projects/fullstack-thumb.jpg',
                'images' => json_encode(['/images/projects/fullstack-1.jpg', '/images/projects/fullstack-2.jpg']),
                'tags' => json_encode(['Full-stack', 'Vue.js', 'Laravel', 'Web Development']),
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 6,
                'completed_at' => '2024-06-30',
                'metadata' => json_encode(['difficulty' => 'intermediate', 'duration' => '8 weeks']),
            ],
        ];

        DB::table('projects')->insert($projects);

        // Testimonials Data
        $testimonials = [
            [
                'key' => 'testimonial_1',
                'type' => 'testimonial',
                'language' => 'en',
                'title_en' => 'Ahmed Mohamed',
                'subtitle_en' => 'Senior Software Engineer at TechCorp',
                'description_en' => 'Ziad is an exceptional developer with deep knowledge of modern web technologies. He delivered our project on time and exceeded our expectations with the quality of his work.',
                'title_ar' => 'أحمد محمد',
                'subtitle_ar' => 'مهندس برمجيات أول في TechCorp',
                'description_ar' => 'زيد هو مطور استثنائي بمعرفة عميقة بتقنيات الويب الحديثة. سلم مشروعنا في الوقت المحدد وتجاوز توقعاتنا بجودة عمله.',
                'sort_order' => 1,
                'category' => 'testimonial',
                'metadata_en' => json_encode(['rating' => 5, 'project' => 'E-commerce Platform']),
                'metadata_ar' => json_encode(['rating' => 5, 'project' => 'منصة التجارة الإلكترونية']),
            ],
            [
                'key' => 'testimonial_1',
                'type' => 'testimonial',
                'language' => 'ar',
                'title_en' => 'Ahmed Mohamed',
                'subtitle_en' => 'Senior Software Engineer at TechCorp',
                'description_en' => 'Ziad is an exceptional developer with deep knowledge of modern web technologies. He delivered our project on time and exceeded our expectations with the quality of his work.',
                'title_ar' => 'أحمد محمد',
                'subtitle_ar' => 'مهندس برمجيات أول في TechCorp',
                'description_ar' => 'زيد هو مطور استثنائي بمعرفة عميقة بتقنيات الويب الحديثة. سلم مشروعنا في الوقت المحدد وتجاوز توقعاتنا بجودة عمله.',
                'sort_order' => 1,
                'category' => 'testimonial',
                'metadata_en' => json_encode(['rating' => 5, 'project' => 'E-commerce Platform']),
                'metadata_ar' => json_encode(['rating' => 5, 'project' => 'منصة التجارة الإلكترونية']),
            ],
            [
                'key' => 'testimonial_2',
                'type' => 'testimonial',
                'language' => 'en',
                'title_en' => 'Sarah Johnson',
                'subtitle_en' => 'Project Manager at Innovate Solutions',
                'description_en' => 'Working with Ziad was a great experience. His expertise in AI and IoT helped us build a smart parking solution that has significantly improved our operations.',
                'title_ar' => 'سارة جونسون',
                'subtitle_ar' => 'مديرة مشاريع في Innovate Solutions',
                'description_ar' => 'العمل مع زيد كان تجربة رائعة. خبرته في الذكاء الاصطناعي وإنترنت الأشياء ساعدتنا في بناء حل وقوف سيارات ذكي حسن بشكل كبير عملياتنا.',
                'sort_order' => 2,
                'category' => 'testimonial',
                'metadata_en' => json_encode(['rating' => 5, 'project' => 'Smart Parking System']),
                'metadata_ar' => json_encode(['rating' => 5, 'project' => 'نظام وقوف سيارات ذكي']),
            ],
            [
                'key' => 'testimonial_2',
                'type' => 'testimonial',
                'language' => 'ar',
                'title_en' => 'Sarah Johnson',
                'subtitle_en' => 'Project Manager at Innovate Solutions',
                'description_en' => 'Working with Ziad was a great experience. His expertise in AI and IoT helped us build a smart parking solution that has significantly improved our operations.',
                'title_ar' => 'سارة جونسون',
                'subtitle_ar' => 'مديرة مشاريع في Innovate Solutions',
                'description_ar' => 'العمل مع زيد كان تجربة رائعة. خبرته في الذكاء الاصطناعي وإنترنت الأشياء ساعدتنا في بناء حل وقوف سيارات ذكي حسن بشكل كبير عملياتنا.',
                'sort_order' => 2,
                'category' => 'testimonial',
                'metadata_en' => json_encode(['rating' => 5, 'project' => 'Smart Parking System']),
                'metadata_ar' => json_encode(['rating' => 5, 'project' => 'نظام وقوف سيارات ذكي']),
            ],
            [
                'key' => 'testimonial_3',
                'type' => 'testimonial',
                'language' => 'en',
                'title_en' => 'Michael Chen',
                'subtitle_en' => 'CTO at StartupHub',
                'description_en' => 'Ziad\'s technical skills and problem-solving abilities are outstanding. He developed our REST API with excellent architecture and security features.',
                'title_ar' => 'مايكل تشين',
                'subtitle_ar' => 'رئيس تقنية المعلومات في StartupHub',
                'description_ar' => 'المهارات التقنية لزيد وقدراته على حل المشكلات ممتازة. طور واجهة برمجة التطبيقات REST الخاصة بنا بهندسة ممتازة وميزات أمان.',
                'sort_order' => 3,
                'category' => 'testimonial',
                'metadata_en' => json_encode(['rating' => 5, 'project' => 'API Development']),
                'metadata_ar' => json_encode(['rating' => 5, 'project' => 'تطوير واجهة برمجة التطبيقات']),
            ],
            [
                'key' => 'testimonial_3',
                'type' => 'testimonial',
                'language' => 'ar',
                'title_en' => 'Michael Chen',
                'subtitle_en' => 'CTO at StartupHub',
                'description_en' => 'Ziad\'s technical skills and problem-solving abilities are outstanding. He developed our REST API with excellent architecture and security features.',
                'title_ar' => 'مايكل تشين',
                'subtitle_ar' => 'رئيس تقنية المعلومات في StartupHub',
                'description_ar' => 'المهارات التقنية لزيد وقدراته على حل المشكلات ممتازة. طور واجهة برمجة التطبيقات REST الخاصة بنا بهندسة ممتازة وميزات أمان.',
                'sort_order' => 3,
                'category' => 'testimonial',
                'metadata_en' => json_encode(['rating' => 5, 'project' => 'API Development']),
                'metadata_ar' => json_encode(['rating' => 5, 'project' => 'تطوير واجهة برمجة التطبيقات']),
            ],
        ];

        DB::table('portfolio_content')->insert($testimonials);

        // Blog Posts Data
        $blogPosts = [
            [
                'key' => 'blog_post_1',
                'type' => 'blog_post',
                'language' => 'en',
                'title_en' => 'Building Scalable REST APIs with Laravel and Sanctum',
                'subtitle_en' => 'A comprehensive guide to creating secure and scalable APIs',
                'description_en' => 'Learn how to build robust RESTful APIs using Laravel framework with Sanctum authentication. This guide covers best practices, security considerations, and performance optimization techniques.',
                'title_ar' => 'بناء واجهات برمجة تطبيقات REST قابلة للتوسع باستخدام Laravel و Sanctum',
                'subtitle_ar' => 'دليل شامل لإنشاء واجهات برمجة تطبيقات آمنة وقابلة للتوسع',
                'description_ar' => 'تعلم كيفية بناء واجهات برمجة تطبيقات RESTful قوية باستخدام إطار عمل Laravel مع مصادقة Sanctum. يغطي هذا الدليل أفضل الممارسات والاعتبارات الأمنية وتقنيات تحسين الأداء.',
                'sort_order' => 1,
                'category' => 'web_development',
                'metadata_en' => json_encode(['reading_time' => '8 min', 'date' => '2024-11-20', 'tags' => ['Laravel', 'API', 'Security']]),
                'metadata_ar' => json_encode(['reading_time' => '8 دقيقة', 'date' => '2024-11-20', 'tags' => ['Laravel', 'API', 'Security']]),
            ],
            [
                'key' => 'blog_post_1',
                'type' => 'blog_post',
                'language' => 'ar',
                'title_en' => 'Building Scalable REST APIs with Laravel and Sanctum',
                'subtitle_en' => 'A comprehensive guide to creating secure and scalable APIs',
                'description_en' => 'Learn how to build robust RESTful APIs using Laravel framework with Sanctum authentication. This guide covers best practices, security considerations, and performance optimization techniques.',
                'title_ar' => 'بناء واجهات برمجة تطبيقات REST قابلة للتوسع باستخدام Laravel و Sanctum',
                'subtitle_ar' => 'دليل شامل لإنشاء واجهات برمجة تطبيقات آمنة وقابلة للتوسع',
                'description_ar' => 'تعلم كيفية بناء واجهات برمجة تطبيقات RESTful قوية باستخدام إطار عمل Laravel مع مصادقة Sanctum. يغطي هذا الدليل أفضل الممارسات والاعتبارات الأمنية وتقنيات تحسين الأداء.',
                'sort_order' => 1,
                'category' => 'web_development',
                'metadata_en' => json_encode(['reading_time' => '8 min', 'date' => '2024-11-20', 'tags' => ['Laravel', 'API', 'Security']]),
                'metadata_ar' => json_encode(['reading_time' => '8 دقيقة', 'date' => '2024-11-20', 'tags' => ['Laravel', 'API', 'Security']]),
            ],
            [
                'key' => 'blog_post_2',
                'type' => 'blog_post',
                'language' => 'en',
                'title_en' => 'IoT Smart Parking: From Concept to Implementation',
                'subtitle_en' => 'Building intelligent parking systems with Arduino and MQTT',
                'description_en' => 'Explore the complete process of developing a smart parking system using IoT technologies. From sensor selection to real-time data processing and user interface design.',
                'title_ar' => 'وقوف السيارات الذكي في إنترنت الأشياء: من المفهوم إلى التنفيذ',
                'subtitle_ar' => 'بناء أنظمة وقوف سيارات ذكية باستخدام Arduino و MQTT',
                'description_ar' => 'استكشف العملية الكاملة لتطوير نظام وقوف سيارات ذكي باستخدام تقنيات إنترنت الأشياء. من اختيار المستشعرات إلى معالجة البيانات في الوقت الفعلي وتصميم واجهة المستخدم.',
                'sort_order' => 2,
                'category' => 'embedded_iot',
                'metadata_en' => json_encode(['reading_time' => '10 min', 'date' => '2024-10-15', 'tags' => ['embedded_iot', 'Arduino', 'Smart City']]),
                'metadata_ar' => json_encode(['reading_time' => '10 دقيقة', 'date' => '2024-10-15', 'tags' => ['embedded_iot', 'Arduino', 'Smart City']]),
            ],
            [
                'key' => 'blog_post_2',
                'type' => 'blog_post',
                'language' => 'ar',
                'title_en' => 'IoT Smart Parking: From Concept to Implementation',
                'subtitle_en' => 'Building intelligent parking systems with Arduino and MQTT',
                'description_en' => 'Explore the complete process of developing a smart parking system using IoT technologies. From sensor selection to real-time data processing and user interface design.',
                'title_ar' => 'وقوف السيارات الذكي في إنترنت الأشياء: من المفهوم إلى التنفيذ',
                'subtitle_ar' => 'بناء أنظمة وقوف سيارات ذكية باستخدام Arduino و MQTT',
                'description_ar' => 'استكشف العملية الكاملة لتطوير نظام وقوف سيارات ذكي باستخدام تقنيات إنترنت الأشياء. من اختيار المستشعرات إلى معالجة البيانات في الوقت الفعلي وتصميم واجهة المستخدم.',
                'sort_order' => 2,
                'category' => 'embedded_iot',
                'metadata_en' => json_encode(['reading_time' => '10 min', 'date' => '2024-10-15', 'tags' => ['embedded_iot', 'Arduino', 'Smart City']]),
                'metadata_ar' => json_encode(['reading_time' => '10 دقيقة', 'date' => '2024-10-15', 'tags' => ['embedded_iot', 'Arduino', 'Smart City']]),
            ],
            [
                'key' => 'blog_post_3',
                'type' => 'blog_post',
                'language' => 'en',
                'title_en' => 'Computer Vision for Autonomous Vehicles',
                'subtitle_en' => 'Lane detection using deep learning and OpenCV',
                'description_en' => 'Deep dive into implementing lane detection systems for autonomous vehicles using computer vision, deep learning, and real-time processing techniques.',
                'title_ar' => 'رؤية الكمبيوتر للمركبات المستقلة',
                'subtitle_ar' => 'كشف المسارات باستخدام التعلم العميق و OpenCV',
                'description_ar' => 'تعمق في تنفيذ أنظمة كشف المسارات للمركبات المستقلة باستخدام رؤية الكمبيوتر والتعلم العميق وتقنيات المعالجة في الوقت الفعلي.',
                'sort_order' => 3,
                'category' => 'ai_ml',
                'metadata_en' => json_encode(['reading_time' => '12 min', 'date' => '2024-09-25', 'tags' => ['Computer Vision', 'AI', 'Autonomous']]),
                'metadata_ar' => json_encode(['reading_time' => '12 دقيقة', 'date' => '2024-09-25', 'tags' => ['Computer Vision', 'AI', 'Autonomous']]),
            ],
            [
                'key' => 'blog_post_3',
                'type' => 'blog_post',
                'language' => 'ar',
                'title_en' => 'Computer Vision for Autonomous Vehicles',
                'subtitle_en' => 'Lane detection using deep learning and OpenCV',
                'description_en' => 'Deep dive into implementing lane detection systems for autonomous vehicles using computer vision, deep learning, and real-time processing techniques.',
                'title_ar' => 'رؤية الكمبيوتر للمركبات المستقلة',
                'subtitle_ar' => 'كشف المسارات باستخدام التعلم العميق و OpenCV',
                'description_ar' => 'تعمق في تنفيذ أنظمة كشف المسارات للمركبات المستقلة باستخدام رؤية الكمبيوتر والتعلم العميق وتقنيات المعالجة في الوقت الفعلي.',
                'sort_order' => 3,
                'category' => 'ai_ml',
                'metadata_en' => json_encode(['reading_time' => '12 min', 'date' => '2024-09-25', 'tags' => ['Computer Vision', 'AI', 'Autonomous']]),
                'metadata_ar' => json_encode(['reading_time' => '12 دقيقة', 'date' => '2024-09-25', 'tags' => ['Computer Vision', 'AI', 'Autonomous']]),
            ],
        ];

        DB::table('portfolio_content')->insert($blogPosts);

        // Portfolio Content Data
        $portfolioContent = [
            [
                'key' => 'hero_title',
                'type' => 'hero',
                'language' => 'en',
                'title_en' => 'Welcome to My Portfolio',
                'subtitle_en' => 'Software Engineer | AI & ML Enthusiast | IoT Developer',
                'description_en' => 'Passionate about creating innovative digital solutions with cutting-edge technologies.',
                'title_ar' => 'مرحباً بكم في معرض أعمالي',
                'subtitle_ar' => 'مهندس برمجيات | متحمس للذكاء الاصطناعي وتعلم الآلة | مطور إنترنت الأشياء',
                'description_ar' => 'شغوف بإنشاء حلول رقمية مبتكرة باستخدام أحدث التقنيات.',
                'sort_order' => 1,
                'category' => 'hero',
            ],
            [
                'key' => 'hero_title',
                'type' => 'hero',
                'language' => 'ar',
                'title_en' => 'Welcome to My Portfolio',
                'subtitle_en' => 'Software Engineer | AI & ML Enthusiast | IoT Developer',
                'description_en' => 'Passionate about creating innovative digital solutions with cutting-edge technologies.',
                'title_ar' => 'مرحباً بكم في معرض أعمالي',
                'subtitle_ar' => 'مهندس برمجيات | متحمس للذكاء الاصطناعي وتعلم الآلة | مطور إنترنت الأشياء',
                'description_ar' => 'شغوف بإنشاء حلول رقمية مبتكرة باستخدام أحدث التقنيات.',
                'sort_order' => 1,
                'category' => 'hero',
            ],
            [
                'key' => 'about_summary',
                'type' => 'about',
                'language' => 'en',
                'title_en' => 'About Me',
                'subtitle_en' => 'Software Engineer & AI Enthusiast',
                'description_en' => 'I am a passionate software engineer with expertise in web development, artificial intelligence, and IoT solutions. My goal is to create innovative digital experiences that solve real-world problems.',
                'title_ar' => 'عني',
                'subtitle_ar' => 'مهندس برمجيات ومتحمس للذكاء الاصطناعي',
                'description_ar' => 'أنا مهندس برمجيات شغوف بالخبرة في تطوير الويب، الذكاء الاصطناعي، وحلول إنترنت الأشياء. هدفي هو خلق تجارب رقمية مبتكرة تحل مشاكل العالم الحقيقي.',
                'sort_order' => 1,
                'category' => 'about',
            ],
            [
                'key' => 'about_summary',
                'type' => 'about',
                'language' => 'ar',
                'title_en' => 'About Me',
                'subtitle_en' => 'Software Engineer & AI Enthusiast',
                'description_en' => 'I am a passionate software engineer with expertise in web development, artificial intelligence, and IoT solutions. My goal is to create innovative digital experiences that solve real-world problems.',
                'title_ar' => 'عني',
                'subtitle_ar' => 'مهندس برمجيات ومتحمس للذكاء الاصطناعي',
                'description_ar' => 'أنا مهندس برمجيات شغوف بالخبرة في تطوير الويب، الذكاء الاصطناعي، وحلول إنترنت الأشياء. هدفي هو خلق تجارب رقمية مبتكرة تحل مشاكل العالم الحقيقي.',
                'sort_order' => 1,
                'category' => 'about',
            ],
        ];

        DB::table('portfolio_content')->insert($portfolioContent);
    }
}
